variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'Bicep-l0204-RG' # Needs to already exist
  location: 'Southeast Asia'
  templateFile: './main.bicep'
  sourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(07ad299f-a06e-4d75-a781-f05ad16d5a76)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) --template-file $(sourceFolder)$(templateFile) \
            --parameters administratorLogin=$(administratorLogin) administratorLoginPassword=$(administratorLoginPassword)
