variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription – MPN(07ad299f-a06e-4d75-a781-f05ad16d5a76)'
    subscriptionId: '07ad299f-a06e-4d75-a781-f05ad16d5a76'
    action: 'DeleteRG'
    resourceGroupName: 'Bicep-l0204-RG'
    location: 'Southeast Asia'
